Bump dependencies
nubank/abracad pull request #14
Opened 2019-10-07 08:03 UTC by hkupty

Two CVEs are indirectly related to abracad through `avro` -> `commons-compress`:
https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-72275
https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-32473

This also ensures tests run for `clojure-1.10` and doesn't force `clojure` as a dependency of this library so newer versions won't pull `clojure-1.9`.

Feel free to drop any of the changes other than bumping avro (and cheshire).

Thanks,
Henry Kupty

2019-10-07 08:05 UTC, hkupty commented
I also embedded a fix for #13 as this was a really quick one-line change.

2019-10-10 08:21 UTC, philomates requested changes
Hey @hkupty thanks for the patch! There is a paren mismatch, but otherwise good to go. Could you also add an entry to the CHANGELOG and then I can more quickly do a release?

2019-10-10 08:21 UTC, philomates commented on project.clj
> +                            [nubank/matcher-combinators "1.2.1"]]
```suggestion
                            [nubank/matcher-combinators "1.2.1"]]}
```

2019-10-10 14:57 UTC, merged

2019-10-10 14:57 UTC, hkupty commented
@philomates Thanks for the response. Couldn't find a CHANGELOG file. Do you want me to add one?

2019-10-10 14:58 UTC, hkupty commented
Amazing! Thanks a lot!

2019-10-10 14:59 UTC, philomates commented
oops, no worries then. Just published it to clojars